apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: containerwebapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: containerwebapp 
    spec:
      containers:
        - name: containerwebapp 
          image: superusers2020registry.azurecr.io/containerwebapp
          ports:
          - containerPort: 8080